### ISSUE TITLE
Add paging to associated objects via /properties endpoint

### ISSUE THREAD

**Issue by chrishenry** [chrishenry/deltanyc-heatseek#36] opened 2016-12-29 17:26 UTC
Many objects associated with properties have 100s of entries. Selecting so many will slow immensely slow down the properties endpoint.

For now, I've simply limited the number of associated objects returned, like so.

```ruby
  has_many :hpd_complaints do
    @object.hpd_complaints.limit(5)
  end
```

**Comment by LKWLaLa** [comment] 2017-03-27 14:47
Closing this issue, because we have it down twice -  it's a duplicate of #42 .

**Closed as completed by LKWLaLa** 2017-03-27 14:47 UTC
Labels: rails
